### ISSUE TITLE
Cant run test suite

### ISSUE THREAD

**Issue by Fedcomp** [sportngin/find_as_hashes#7]
Cannot run test suite, readme says it's just `rake test` but this is what i get (after bundle update of course)
```
user@user-pc:~/find_as_hashes$ rake test
/home/user/.rvm/rubies/ruby-2.2.1/bin/ruby -I"lib:lib:test"  "/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/rake_test_loader.rb" "test/active_resource_test.rb" "test/find_as_hashes_test.rb" 
/home/user/.rvm/gems/ruby-2.2.1/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `require': cannot load such file -- test/unit (LoadError)
        from /home/user/.rvm/gems/ruby-2.2.1/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `block in require'
        from /home/user/.rvm/gems/ruby-2.2.1/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:214:in `load_dependency'
        from /home/user/.rvm/gems/ruby-2.2.1/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `require'
        from /home/user/find_as_hashes/test/test_helper.rb:2:in `<top (required)>'
        from /home/user/find_as_hashes/test/active_resource_test.rb:1:in `require'
        from /home/user/find_as_hashes/test/active_resource_test.rb:1:in `<top (required)>'
        from /home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/rake_test_loader.rb:15:in `require'
        from /home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/rake_test_loader.rb:15:in `block in <main>'
        from /home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/rake_test_loader.rb:4:in `select'
        from /home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1): [ruby -I"lib:lib:test"  "/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/rake_test_loader.rb" "test/active_resource_test.rb" "test/find_as_hashes_test.rb" ]
/home/user/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/home/user/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)
```

**Comment by jphenow** [comment]
@Fedcomp if you pull latest master you should be good again. Thanks for posting!
